version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tn-cloud-9-app-framework"
    assignees:
      - "tn-cloud-9-app-framework"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # npm dependencies for TypeScript projects
  - package-ecosystem: "npm"
    directory: "/acr-image-promotion-action"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tn-cloud-9-app-framework"
    assignees:
      - "tn-cloud-9-app-framework"
    labels:
      - "dependencies"
      - "typescript"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: "increase"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  # Terraform dependencies
  - package-ecosystem: "terraform"
    directory: "/terraform-azurerm-acr-platform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tn-cloud-9-app-framework"
    assignees:
      - "tn-cloud-9-app-framework"
    labels:
      - "dependencies"
      - "terraform"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Docker dependencies (if any Dockerfiles exist)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "tn-cloud-9-app-framework"
    assignees:
      - "tn-cloud-9-app-framework"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"