format: tty
failure-threshold: warning

ignored:
  - DL3008  # Pin versions in apt get install
  - DL3009  # Delete the apt-get lists after installing something
  - DL3015  # Avoid additional packages by specifying `--no-install-recommends`
  - DL3059  # Multiple consecutive `RUN` instructions

trustedRegistries:
  - docker.io
  - mcr.microsoft.com
  - ghcr.io
  - quay.io

override:
  error:
    - DL3002  # Last USER should not be root
    - DL3020  # Use COPY instead of ADD for files and folders
    - DL3025  # Use arguments JSON notation for CMD and ENTRYPOINT arguments
  warning:
    - DL3003  # Use WORKDIR to switch to a directory
    - DL3016  # Pin versions in npm
    - DL3018  # Pin versions in apk add
  info:
    - DL3032  # `yum clean all` missing after yum command
    - DL3033  # Specify version with `yum install -y <package>-<version>`