name: 'Promote Sandbox'
description: 'Promotes container images within the sandbox registry for experimentation'
author: 'BrightCloud Platform Team'

inputs:
  team-name:
    description: 'Team name for image organization'
    required: true
  image-name:
    description: 'Name of the container image'
    required: true
  source-tag:
    description: 'Source image tag to promote'
    required: true
  target-tag:
    description: 'Target image tag (defaults to source-tag if not provided)'
    required: false
  sandbox-registry:
    description: 'Sandbox registry URL'
    required: false
    default: 'brightcloudsandbox.azurecr.io'
  azure-client-id:
    description: 'Azure service principal client ID (for OIDC)'
    required: true
  azure-tenant-id:
    description: 'Azure tenant ID'
    required: true
  azure-subscription-id:
    description: 'Azure subscription ID'
    required: true
  resource-group-name:
    description: 'Azure resource group containing the container registry'
    required: true
  dry-run:
    description: 'Perform validation without actual promotion'
    required: false
    default: 'false'
  force:
    description: 'Force promotion even if target image exists'
    required: false
    default: 'false'

outputs:
  source-image:
    description: 'Full source image reference'
    value: ${{ steps.promote.outputs.source-image }}
  target-image:
    description: 'Full target image reference'
    value: ${{ steps.promote.outputs.target-image }}
  target-digest:
    description: 'Digest of the promoted image'
    value: ${{ steps.promote.outputs.target-digest }}

runs:
  using: composite
  steps:
    - name: Promote Image in Sandbox
      id: promote
      uses: ../
      with:
        source-registry: ${{ inputs.sandbox-registry }}
        target-registry: ${{ inputs.sandbox-registry }}
        source-environment: 'sandbox'
        target-environment: 'sandbox'
        team-name: ${{ inputs.team-name }}
        image-name: ${{ inputs.image-name }}
        source-tag: ${{ inputs.source-tag }}
        target-tag: ${{ inputs.target-tag || inputs.source-tag }}
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}
        resource-group-name: ${{ inputs.resource-group-name }}
        dry-run: ${{ inputs.dry-run }}
        force: ${{ inputs.force }}