name: 'Promote Same Registry'
description: 'Promotes container images between environments in the same registry'
author: 'BrightCloud Platform Team'

inputs:
  registry:
    description: 'Registry URL (e.g., brightcloudnonprod-abc123.azurecr.io)'
    required: true
  source-environment:
    description: 'Source environment (pr, dev, perf, preproduction, production)'
    required: true
  target-environment:
    description: 'Target environment (dev, perf, preproduction, production)'
    required: true
  image-name:
    description: 'Name of the image to promote (without registry/environment prefix)'
    required: true
  source-tag:
    description: 'Source image tag to promote'
    required: true
  target-tag:
    description: 'Target image tag (defaults to source-tag if not provided)'
    required: false
  azure-client-id:
    description: 'Azure service principal client ID (for OIDC)'
    required: true
  azure-tenant-id:
    description: 'Azure tenant ID'
    required: true
  azure-subscription-id:
    description: 'Azure subscription ID'
    required: true
  dry-run:
    description: 'Perform validation without actual promotion'
    required: false
    default: 'false'
  force:
    description: 'Force promotion even if target image exists'
    required: false
    default: 'false'

outputs:
  source-image:
    description: 'Full source image reference'
    value: ${{ steps.promote.outputs.source-image }}
  target-image:
    description: 'Full target image reference'
    value: ${{ steps.promote.outputs.target-image }}
  promotion-result:
    description: 'Result of the promotion operation'
    value: ${{ steps.promote.outputs.result }}
  target-digest:
    description: 'SHA256 digest of the promoted image'
    value: ${{ steps.promote.outputs.target-digest }}

runs:
  using: 'composite'
  steps:
    - name: Promote Image Between Environments
      id: promote
      uses: ../
      with:
        source-registry: ${{ inputs.registry }}
        target-registry: ${{ inputs.registry }}
        source-environment: ${{ inputs.source-environment }}
        target-environment: ${{ inputs.target-environment }}
        image-name: ${{ inputs.image-name }}
        source-tag: ${{ inputs.source-tag }}
        target-tag: ${{ inputs.target-tag || inputs.source-tag }}
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}
        dry-run: ${{ inputs.dry-run }}
        force: ${{ inputs.force }}

branding:
  icon: 'refresh-cw'
  color: 'purple'